### ISSUE TITLE
control that times out is not coming through as an error, but instead being (silently) ignored

### ISSUE THREAD

**Issue by fgomesz** [turbot/steampipe-mod-aws-compliance#557] opened 2023-02-06 19:03 UTC
**Describe the bug**
Hi I'm having a strange behaviour, i'm running compliance checks on an AWS account. Sometimes I receive results from https://hub.steampipe.io/mods/turbot/aws_compliance/queries/ecs_task_definition_container_non_privileged other times I don't. I've set the "--query-timeout=0", but there are no results from that control query. If I execute the control by itself, there are no issues at all.

**Steampipe version (`steampipe -v`)**
Example: v0.18.3

**Plugin version (`steampipe plugin list`)**
Example: v0.92.1

**To reproduce**
steampipe check benchmark.my_report_aws --export bigtest.json --output brief --query-timeout 0

**Expected behavior**
It is expected that all query data is returned in the control results.

**Additional context**
[QueryAffected](https://hub.steampipe.io/mods/turbot/aws_compliance/queries/ecs_task_definition_container_non_privileged)

**Comment by cbruno10** [comment] 2023-02-06 20:27
Hey @fgomesz , are there other controls you're seeing this unexpected behaviour with (consistently or inconsistently)? Or is it always just this control?

Also, can you please share the exact output you get when you encounter unexpected results and your `aws.spc` config file (with any sensitive information removed)? This will help us see if we can reproduce, either with this control, or with others.

Thanks!

**Comment by fgomesz** [comment] 2023-02-08 12:17
The strange thing I've noticed here was the name with ":" which is not very common

**Comment by fgomesz** [comment] 2023-02-08 18:54
but there is more  I run aws benchmarks on an AWS cloud, however I keep getting different results for every time I run the scans. I'm using the latest version of steampipe to run aws cloud compliance benchmarks. For the authentication, I use temporary access keys from Okta. I use --query-timeouts set to 0, the scans are very fast and take less than 60 seconds to run. From the logs, I can see these 2 error messages quite often  "2023-02-08 13:22:18.430 UTC [WARN]  hub: columnFromVar failed - could not get conversion info for index 4045, returning empty string 2023-02-08 13:22:18.430 UTC [WARN]  hub: qualFromBoolExpr failed to get column from variable &{119}" and "2023-02-08 13:51:57.793 UTC [WARN]  hub: goFdwAbortCallback failed with panic: runtime error: invalid memory address or nil pointer dereference
2023-02-08 13:51:57.963 UTC [WARN]  hub: stream receive error rpc error: code = Unknown desc = operation error CloudTrail: DescribeTrails, https response error StatusCode: 400, RequestID: 3b8f61a4-0542-4e08-88a2-c8c82890a267, api error ExpiredTokenException: The security token included in the request is expired (0xc00056cd10)
2023-02-08 13:51:57.963 UTC [1871201] ERROR:  rpc error: code = Unknown desc = operation error CloudTrail: DescribeTrails, https response error StatusCode: 400, RequestID: 3b8f61a4-0542-4e08-88a2-c8c82890a267, api error ExpiredTokenException: The security token included in the request is expired". okay there has to be something on steampipe check benchmarks, because I've ran 3 times the same benchmark cis_v140 https://hub.steampipe.io/mods/turbot/aws_compliance/dashboards/benchmark.cis_v140 and I got different results when running it 3 times. My custom benchmark is way heavier, in the queries level, and this error is shown more often but the results that are missing from the benchmark scan appear using the same temporary Okta credentials when executing the specific control or query

**Comment by misraved** [comment] 2023-02-08 19:42
Hello @fgomesz, apologies for the inconvenience.

We have identified that this could be a potential bug in the Steampipe CLI.

You could use the `max-parallel` parameter to reduce the concurrent database connections. For instance, you could try `steampipe check benchmark.cis_v150_5 --max-parallel=1` command while executing your benchmarks or controls to avoid this issue 👍.

We will look to get this fix out as soon as possible. Thanks for adding so many details to the issue, it has certainly helped us to narrow down the problem 👍.

**Comment by fgomesz** [comment] 2023-02-09 09:55
Hi @misraved ,

it's true we got to the same conclusion, disabling the cache, max parallel connections to DB set to 1 and disabling the query timeout gives a scan with less errors.

**Comment by rajlearner17** [comment] 2023-02-20 13:56
@fgomesz I would request to try it with the latest AWS plugin, i.e. `0.93.0`, and check if the issue you reported is addressed.

**Comment by bigdatasourav** [comment] 2023-06-27 05:12
Hey @fgomesz, We are closing this issue because we have not heard from you. Please feel free to reopen the issue if you want to share or discuss anything.

**Closed by bigdatasourav** 2023-06-27 05:12 UTC
Labels: bug
